Fix gauge (extremes, title)
dshmelev/MTTP-SolarMetrics pull request #4
Opened 2016-09-28 07:28 UTC by LLIMEJI

2016-09-30 05:31 UTC, dshmelev requested changes

2016-09-30 05:31 UTC, dshmelev commented on frontend/indicators/indicators.js
> +        $.getJSON('http://sosvetom.ru/_api/get_metrics/?num=100&col=1',
Тогда уж http://sosvetom.ru/_api/get_metrics/?num=2&col=1

2016-09-30 05:31 UTC, dshmelev commented on frontend/indicators/indicators.js
> +                    chartToUpdate.yAxis[0].setExtremes(0,newVal+100);
Зачем +100?

2016-09-30 05:31 UTC, dshmelev commented on frontend/indicators/indicators.js
> +                    chartToUpdate.yAxis[0].setExtremes(0,1100);
Не надо тут хардкодить. Максимальное значение возьми из yAxis->max

2016-09-30 05:31 UTC, dshmelev commented on frontend/indicators/indicators.js
> +                if (newVal >= 1100) {
Не надо тут хардкодить. Максимальное значение возьми из yAxis->max

2016-09-30 05:33 UTC, LLIMEJI commented on frontend/indicators/indicators.js
> +                    chartToUpdate.yAxis[0].setExtremes(0,newVal+100);
Чтобы стрелка целый день не лежала на другом богу

2016-09-30 05:37 UTC, dshmelev commented on frontend/indicators/indicators.js
> +                    chartToUpdate.yAxis[0].setExtremes(0,newVal+100);
Погоди.. если data => 1100, то мы добавляем к ней 100 и рисуем показания?
Т.е. 1200, 1300, 1400, 1500 и т.д...
По-моему это не валидные значения для этого графика. Разве нет?

2016-09-30 05:42 UTC, LLIMEJI commented on frontend/indicators/indicators.js
> +                if (newVal >= 1100) {
Тогда так выйдет:
value = 1400, max = 1400
value 1300, max = 1100

2016-09-30 07:41 UTC, anlcnt commented on frontend/indicators/indicators.js
> +                    chartToUpdate.yAxis[0].setExtremes(0,newVal+100);
Вообще, вроде как, всё валидно было. Убрал, чтобы не мозолило глаза :)

2016-10-05 13:46 UTC, dshmelev approved these changes

2016-10-05 13:46 UTC, merged